(ns votingbuddy.db_initialization
  (:require [votingbuddy.auth :as auth]))

;; (auth/create-user! "testuser" "testpass1")
;; (auth/create-user! "democrat_user" "testpass1")
;; (auth/create-user! "republican_user" "testpass1")
;; (auth/create-user! "conservative_user" "testpass1")
;; (auth/create-user! "medicalfreedom_user" "testpass1")
;; (auth/create-user! "commonsense_user" "testpass1")
;; (auth/create-user! "diversity_user" "testpass1")
;; (auth/create-user! "publicsafety_user" "testpass1")
;; (auth/create-user! "publicservice_user" "testpass1")
;; (auth/create-user! "boroparkflatbsh_user" "testpass1")
;; (auth/create-user! "teamtrump_user" "testpass1")
;; (auth/create-user! "betterflushing_user" "testpass1")
;; (auth/create-user! "safestreetssi_user" "testpass1")
;; (auth/create-user! "animalwelfare_user" "testpass1")
;; (auth/create-user! "kebreau4council_user" "testpass1")
;; (auth/create-user! "workingfamilies_user" "testpass1")
;; (auth/create-user! "wethepeople_user" "testpass1")
;; (auth/create-user! "cleanupny_user" "testpass1")
;; (auth/create-user! "artsandculture_user" "testpass1")
;; (auth/create-user! "madashell_user" "testpass1")
;; (auth/create-user! "parentparty_user" "testpass1")
;; (auth/create-user! "taxpayersunite_user" "testpass1")